CXX ?= clang++

all:
	$(CXX) -std=c++20 --precompile -x c++-module foo.cpp -o foo.pcm
	$(CXX) -std=c++20 cppmodule.cpp -fmodule-file=foo=foo.pcm foo.pcm -o cppmodule

clean:
	rm -f foo.pcm cppmodule

.PHONY: all clean
